### ISSUE TITLE
Cannot Build APK Issue

### ISSUE THREAD

**Issue by nscxp2005** [yifanlu/PSXperia#15]
I get the following error message in the Terminal on Ubuntu 10.10

java.io.FileNotFoundException: temp.dat (Too many open files)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:209)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:99)
    at com.yifanlu.PSXperiaTool.PSImageCreate.splitPart(PSImageCreate.java:54)
    at com.yifanlu.PSXperiaTool.PSImageCreate.compress(PSImageCreate.java:46)
    at com.yifanlu.PSXperiaTool.PSXperiaTool.generateImage(PSXperiaTool.java:159)
    at com.yifanlu.PSXperiaTool.PSXperiaTool.startBuild(PSXperiaTool.java:61)
    at com.yifanlu.PSXperiaTool.Interface.GUI$12.run(GUI.java:695)
    at java.lang.Thread.run(Thread.java:636)

I hope this can be resolved.

NSCXP2005

**Comment by yifanlu** [comment]
Solved in 1.0 release (I think). If not, please reopen the issue. (You can download 1.0 from the downloads section).

**Comment by nscxp2005** [comment]
Issue has been fixed, but I get the following error:

[D] Running command: [./aapt-linux package -f -F /home/nscxp/Desktop/PSX/com.sony.playstation.NCXA56789_1.apk.unsigned -S ./.psxperia.346/res -M ./.psxperia.346/assets/AndroidManifest.xml -I ./android-framework.jar ./.psxperia.346]

[E] Cannot build APK! Java says: Cannot run program "./aapt-linux": java.io.IOException: error=12, Cannot allocate memory

**Comment by nscxp2005** [comment]
Issue fully resolved
