### ISSUE TITLE
Problem Extracting Crash 1 Apk

### ISSUE THREAD

**Issue by Dgg228** [yifanlu/PSXperia#53]
While using v1.0 eveything works fine but when using v2.0 when the extraction process gets to Patching XML Strings with tags it says "[E] Cannot extract APK! Java says C:\Users\Deaven\Desktop\PSXperia 2.0.\data\config (Access is denied)"
I am using Win 7 64 bit. Any ideas on what is causing this?

Here is the whole log as well

C:\Users\Deaven\Desktop\PSXperia 2.0>java -jar PSXperiaTool.jar
Dec 06, 2011 1:53:56 AM brut.androlib.res.AndrolibResources loadMainPkg
INFO: Loading resource table...
Dec 06, 2011 1:53:56 AM brut.androlib.res.AndrolibResources loadMainPkg
INFO: Loaded.
Dec 06, 2011 1:53:56 AM brut.androlib.res.AndrolibResources loadFrameworkPkg
INFO: Loading resource table from file: C:\Users\Deaven\apktool\framework\1.apk
Dec 06, 2011 1:53:59 AM brut.androlib.res.AndrolibResources loadFrameworkPkg
INFO: Loaded.
Dec 06, 2011 1:53:59 AM brut.androlib.res.AndrolibResources decode
INFO: Decoding file-resources...
Dec 06, 2011 1:53:59 AM brut.androlib.res.AndrolibResources decode
INFO: Decoding values_/_ XMLs...
Dec 06, 2011 1:53:59 AM brut.androlib.res.AndrolibResources decode
INFO: Done.
java.io.FileNotFoundException: C:\Users\Deaven\Desktop\Delete\config (Access is
denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at ie.wombat.jbdiff.JBPatch.bspatch(JBPatch.java:72)
        at com.yifanlu.PSXperiaTool.Extractor.CrashBandicootExtractor.patchEmula
tor(CrashBandicootExtractor.java:260)
        at com.yifanlu.PSXperiaTool.Extractor.CrashBandicootExtractor.extractApk
(CrashBandicootExtractor.java:73)
        at com.yifanlu.PSXperiaTool.Interface.GUI$13.run(GUI.java:771)
        at java.lang.Thread.run(Thread.java:722)

**Comment by domcarlos** [comment]
Had the same problem...
No answers?
