### ISSUE TITLE
Error in generating output

### ISSUE THREAD

**Issue by JonnyMe** [yifanlu/PSXperia#68]
When I run Convert it creates data but crashes when generating apk with this error:

<b>Cannot build AKP! Java says: Executable did not return without error</b>

I'm running Win 7 64bit, tool at version 1.0, aapt path is set to PATH variable, game image is .img

Here the log:

<code>
[I] PSXperiaTool initialized, outputting to: D:\psxperia\MEDIA\Dragonball
[I] Starting build with PSXPeria Converter version 1.0
[I] Checking to make sure all files are there.
[D] Done checking data.
[I] Creating temporary directory.
[D] Created temporary directory at, ..psxperia.488
[I] Copying icon if needed.
[D] Done copying icon from D:\psxperia\MEDIA\copertine\dragonball.png
[I] Replacing strings.
[D] Replacing strings in XML data.
[D] Writing to temporary file: ..psxperia.488\assets\AndroidManifest.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: ..psxperia.488\assets\ZPAK\metadata.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: ..psxperia.488\res\values\strings.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: ..psxperia.488\ZPAK\metadata.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Done with string replacement.
[D] Done replacing strings.
[I] Generating PSImage.
[I] Beginning PSImage compression.
[I] Generating image TOC.
[D] Done generating PSImage
[I] Generating ZPAK.
[I] Generating zpak file from directory ..psxperia.488\ZPAK with compression =
false
[D] Done with ZPAK creation.
[D] Done generating ZPAK at ..psxperia.488\NCXA00000_1.zpak
[I] Generating default ZPAK.
[I] Generating zpak file from directory ..psxperia.488\assets\ZPAK with compres
sion = true
[D] Done with ZPAK creation.
[D] Done generating default ZPAK at ..psxperia.488\assets\NCXA00000_1.zpak
[I] Done processing, generating output.
[D] Moving files around.
[D] Running command: [.\aapt-windows.exe package -f -F D:\psxperia\MEDIA\Dragonb
all\com.sony.playstation.NCXA00000_1.apk.unsigned -S ..psxperia.488\res -M ..p
sxperia.488\assets\AndroidManifest.xml -I .\android-framework.jar ..psxperia.48
8]
[D] ERROR: resource directory '..psxperia.488\res' does not exist
[E] Cannot build APK! Java says: Executable did not return without error.
java.io.IOException: Executable did not return without error.
        at com.yifanlu.PSXperiaTool.ApkBuilder.runCmdWithOutput(ApkBuilder.java:
116)
        at com.yifanlu.PSXperiaTool.ApkBuilder.buildApk(ApkBuilder.java:85)
        at com.yifanlu.PSXperiaTool.PSXperiaTool.generateOutput(PSXperiaTool.jav
a:207)
        at com.yifanlu.PSXperiaTool.PSXperiaTool.startBuild(PSXperiaTool.java:64
)
        at com.yifanlu.PSXperiaTool.Interface.GUI$12.run(GUI.java:696)
        at java.lang.Thread.run(Unknown Source)
</code>

**Comment by JonnyMe** [comment]
I close the issue, I managed to get out and I solved, it was because of different version between apk and zpak.
